### PR TITLE
Upgrade the metrics to latest version 3.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by comcastrong**
Hey,
   I upgraded it to use the latest metrics version 3.0.0-SNAPSHOT. It allow me to use the newGauge api for gaue without using counter to simulate it.
  If you have any questions, please let me know.
  Thanks
  Yongjun Rong

### CODE REVIEW

**Comment by sethfitz** [comment]
Great.  I'm glad to see that this is possible.  However, I'd rather wait 'til 3.0.0 is released and then apply the change, as the implementation doesn't affect users of the service (right? or does this fix #2).

For reference, Coda mentioned that snapshot releases are also available from:

``` xml
     <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

**Comment by comcastrong** [comment]
It also fixed the issue #2. But it need some changes on the metrics side. I already sent a pull to metrics too. Hope they accept it.

**Comment by sethfitz** [comment]
How does `ValueGauge` fix #2?  Nothing in your `metrics` PR seems to reset the value of the `Gauge` at any interval (I was thinking that there were other changes in 3.0.0-SNAPSHOT that may have introduced a mechanism to do that).

**Comment by comcastrong** [comment]
This is the change I made in metricsd MetricsServiceHandler.

```
case GAUGE_METRIC_TYPE =>
              log.debug("Updating gauge '%s' with %d", metricName, value)
              // use a counter to simulate a gauge
              //val counter = Metrics.newCounter(new MetricName("metrics", "gauge", metricName))
              //counter.clear()
              //counter.inc(value)
             // Change it to use the Metrics.newGauge API. By Yongjun Rong
             Metrics.newGauge(new MetricName("metrics", "gauge", metricName),value);
```

In metrics side, I created this new ValueGauge class

```
package com.yammer.metrics.core;

import java.util.concurrent.atomic.AtomicLong;

/**
 * An Gauge with Long number as the value. Added by Yongjun Rong
 */
public class ValueGauge extends Gauge<Long> {
    private final AtomicLong value;

    public ValueGauge() {
        this.value = new AtomicLong(0L);
    }

    public ValueGauge(Long val) {
        this.value = new AtomicLong(val.longValue());
    }

    /**
     * Set the value to a give value.
     */
    public void set(Long val) {
        value.set(val.longValue());
    }

    @Override
    public Long value() {
            return Long.valueOf(value.get());
    }

}
```

In metrics Metrics class, I created a new newGauge api to return a ValueGauge

```
/**
     * Given a new gauge Long value, registers it under the given metric name.
     *
     * @param metricName the name of the metric
     * @param value    the gauge value
     * @return {@code ValueGauge}
     */
    public static ValueGauge newGauge(MetricName metricName,
                                        Long metricValue) {

        ValueGauge gauge = (ValueGauge) DEFAULT_REGISTRY.newGauge(metricName, new ValueGauge());
        gauge.set(metricValue);
        return gauge;
    }
```

And it set the new value to the gauge.

**Comment by comcastrong** [comment]
I might miss understand your issue #2. In my case, it will be reset to 0 from an outside request.

**Comment by sethfitz** [comment]
It already worked that way.  #2 is about metricsd resetting the gauge if it wasn't updated since the most recent flush (having a concrete `Gauge` type is gravy).

**Comment by comcastrong** [comment]
It was working when you use the counter to simulate the gauge. But not working when I use the gauge API.

**Comment by sethfitz** [comment]
Good to know; I'll keep that in mind when I update to 3.0.x.  In the meantime, I'm closing this.

**Pull request closed without merging**
